version: "3"
services: 
    node-app:
        build: .
        ports:
            - 3000:3000
        environment: 
            - PORT=3000
            - MESSAGE=Default Hello World!!        
        # env_file: 
        #     - ./.env