version: "3"
services: 
    node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app:ro
            # Annonymous volume to not overwrite node_modules locally
            - /app/node_modules 
        environment: 
            - MESSAGE=Dev Hello World!!
            - NODE_ENV=development
            - MONGO_USER=admin
            - MONGO_PASSWORD=changeme
            - SESSION_SECRET=super-safe-secret
        entrypoint: npm run dev
    mongodb:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=changeme
        volumes: 
            - mongo-db:/data/db
